[2025-09-15T10:01:57.070+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_metrics_calculator.calculate_metrics manual__2025-09-15T10:01:46.442990+00:00 [queued]>
[2025-09-15T10:01:57.091+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_metrics_calculator.calculate_metrics manual__2025-09-15T10:01:46.442990+00:00 [queued]>
[2025-09-15T10:01:57.091+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-09-15T10:01:57.091+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-09-15T10:01:57.092+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-09-15T10:01:57.136+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): calculate_metrics> on 2025-09-15 10:01:46.442990+00:00
[2025-09-15T10:01:57.155+0000] {standard_task_runner.py:55} INFO - Started process 205 to run task
[2025-09-15T10:01:57.163+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_metrics_calculator', 'calculate_metrics', 'manual__2025-09-15T10:01:46.442990+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmp_je1p6fi']
[2025-09-15T10:01:57.165+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask calculate_metrics
[2025-09-15T10:01:57.343+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_metrics_calculator.calculate_metrics manual__2025-09-15T10:01:46.442990+00:00 [running]> on host 74538f231de5
[2025-09-15T10:01:57.579+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_metrics_calculator
AIRFLOW_CTX_TASK_ID=calculate_metrics
AIRFLOW_CTX_EXECUTION_DATE=2025-09-15T10:01:46.442990+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-15T10:01:46.442990+00:00
[2025-09-15T10:01:57.598+0000] {logging_mixin.py:137} INFO - ‚ùå Error reading CSV: [Errno 2] No such file or directory: '/home/jay/login-signup/b.end/uploads/jay.csv'
[2025-09-15T10:01:57.599+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flow.py", line 12, in calculate_csv_metrics
    df = pd.read_csv(CSV_FILE_PATH)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/home/jay/login-signup/b.end/uploads/jay.csv'
[2025-09-15T10:01:57.630+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=csv_metrics_calculator, task_id=calculate_metrics, execution_date=20250915T100146, start_date=20250915T100157, end_date=20250915T100157
[2025-09-15T10:01:57.667+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 49 for task calculate_metrics ([Errno 2] No such file or directory: '/home/jay/login-signup/b.end/uploads/jay.csv'; 205)
[2025-09-15T10:01:57.698+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-09-15T10:01:57.740+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
