[2025-09-10T07:26:27.188+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_validation_pipeline_v1.load_path_task manual__2025-09-10T07:26:23.019064+00:00 [queued]>
[2025-09-10T07:26:27.207+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_validation_pipeline_v1.load_path_task manual__2025-09-10T07:26:23.019064+00:00 [queued]>
[2025-09-10T07:26:27.208+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-09-10T07:26:27.208+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-09-10T07:26:27.208+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-09-10T07:26:27.233+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_path_task> on 2025-09-10 07:26:23.019064+00:00
[2025-09-10T07:26:27.248+0000] {standard_task_runner.py:55} INFO - Started process 175 to run task
[2025-09-10T07:26:27.257+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_validation_pipeline_v1', 'load_path_task', 'manual__2025-09-10T07:26:23.019064+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmpmv7b3z_v']
[2025-09-10T07:26:27.258+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask load_path_task
[2025-09-10T07:26:27.384+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_validation_pipeline_v1.load_path_task manual__2025-09-10T07:26:23.019064+00:00 [running]> on host 31c2b52cdb43
[2025-09-10T07:26:27.510+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_validation_pipeline_v1
AIRFLOW_CTX_TASK_ID=load_path_task
AIRFLOW_CTX_EXECUTION_DATE=2025-09-10T07:26:23.019064+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-10T07:26:23.019064+00:00
[2025-09-10T07:26:27.520+0000] {logging_mixin.py:137} INFO - Checking: /home/jay/login-signup/***_project/uploads/jay.csv
[2025-09-10T07:26:27.522+0000] {logging_mixin.py:137} INFO - Exists? False
[2025-09-10T07:26:27.522+0000] {logging_mixin.py:137} INFO - CSV file not found.
[2025-09-10T07:26:27.522+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flow.py", line 30, in task_load_path
    raise FileNotFoundError("CSV file not found.")
FileNotFoundError: CSV file not found.
[2025-09-10T07:26:27.540+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_validation_pipeline_v1, task_id=load_path_task, execution_date=20250910T072623, start_date=20250910T072627, end_date=20250910T072627
[2025-09-10T07:26:27.565+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task load_path_task (CSV file not found.; 175)
[2025-09-10T07:26:27.589+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-09-10T07:26:27.638+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
