[2025-09-04T05:30:51.324+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-09-04T05:30:51.357+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-09-04T05:30:51.357+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-09-04T05:30:51.358+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-09-04T05:30:51.358+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-09-04T05:30:51.391+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): inaccurate> on 2025-09-01 00:00:00+00:00
[2025-09-04T05:30:51.401+0000] {standard_task_runner.py:55} INFO - Started process 104 to run task
[2025-09-04T05:30:51.409+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmpusc9q06m']
[2025-09-04T05:30:51.410+0000] {standard_task_runner.py:83} INFO - Job 192: Subtask inaccurate
[2025-09-04T05:30:51.622+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2025-09-01T00:00:00+00:00 [running]> on host caf234be515d
[2025-09-04T05:30:51.784+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2025-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-01T00:00:00+00:00
[2025-09-04T05:30:51.792+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-09-04T05:30:51.795+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2025-09-04T05:30:51.829+0000] {subprocess.py:86} INFO - Output:
[2025-09-04T05:30:51.830+0000] {subprocess.py:93} INFO - inaccurate
[2025-09-04T05:30:51.831+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-04T05:30:51.909+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20250901T000000, start_date=20250904T053051, end_date=20250904T053051
[2025-09-04T05:30:51.986+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-09-04T05:30:52.060+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
