[2025-09-04T06:47:37.399+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-09-04T06:47:37.414+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-09-04T06:47:37.414+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-09-04T06:47:37.414+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-09-04T06:47:37.415+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-09-04T06:47:37.443+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): inaccurate> on 2025-09-03 00:00:00+00:00
[2025-09-04T06:47:37.450+0000] {standard_task_runner.py:55} INFO - Started process 577 to run task
[2025-09-04T06:47:37.455+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmp5yo7bulu']
[2025-09-04T06:47:37.456+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask inaccurate
[2025-09-04T06:47:37.530+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2025-09-03T00:00:00+00:00 [running]> on host 6789badf8728
[2025-09-04T06:47:37.607+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2025-09-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-09-03T00:00:00+00:00
[2025-09-04T06:47:37.614+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-09-04T06:47:37.615+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2025-09-04T06:47:37.629+0000] {subprocess.py:86} INFO - Output:
[2025-09-04T06:47:37.635+0000] {subprocess.py:93} INFO - inaccurate
[2025-09-04T06:47:37.636+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-04T06:47:37.679+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20250903T000000, start_date=20250904T064737, end_date=20250904T064737
[2025-09-04T06:47:37.747+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-09-04T06:47:37.779+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
