[2025-09-12T09:17:41.529+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_validation_pipeline_v1.load_path_task manual__2025-09-12T09:17:36.941768+00:00 [queued]>
[2025-09-12T09:17:41.542+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: csv_validation_pipeline_v1.load_path_task manual__2025-09-12T09:17:36.941768+00:00 [queued]>
[2025-09-12T09:17:41.543+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-09-12T09:17:41.543+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2025-09-12T09:17:41.543+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-09-12T09:17:41.559+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_path_task> on 2025-09-12 09:17:36.941768+00:00
[2025-09-12T09:17:41.569+0000] {standard_task_runner.py:55} INFO - Started process 864 to run task
[2025-09-12T09:17:41.573+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'csv_validation_pipeline_v1', 'load_path_task', 'manual__2025-09-12T09:17:36.941768+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/flow.py', '--cfg-path', '/tmp/tmpebgaodv7']
[2025-09-12T09:17:41.574+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask load_path_task
[2025-09-12T09:17:41.657+0000] {task_command.py:388} INFO - Running <TaskInstance: csv_validation_pipeline_v1.load_path_task manual__2025-09-12T09:17:36.941768+00:00 [running]> on host 01758fe2635d
[2025-09-12T09:17:41.742+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_validation_pipeline_v1
AIRFLOW_CTX_TASK_ID=load_path_task
AIRFLOW_CTX_EXECUTION_DATE=2025-09-12T09:17:36.941768+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-12T09:17:36.941768+00:00
[2025-09-12T09:17:41.745+0000] {logging_mixin.py:137} INFO - Checking: /home/jay/login-signup/***_project/uploads/jay.csv
[2025-09-12T09:17:41.747+0000] {logging_mixin.py:137} INFO - Exists? False
[2025-09-12T09:17:41.748+0000] {logging_mixin.py:137} INFO - CSV file not found.
[2025-09-12T09:17:41.748+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flow.py", line 30, in task_load_path
    raise FileNotFoundError("CSV file not found.")
FileNotFoundError: CSV file not found.
[2025-09-12T09:17:41.759+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_validation_pipeline_v1, task_id=load_path_task, execution_date=20250912T091736, start_date=20250912T091741, end_date=20250912T091741
[2025-09-12T09:17:41.779+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task load_path_task (CSV file not found.; 864)
[2025-09-12T09:17:41.829+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-09-12T09:17:41.864+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
